# Default configuration for the Creal & Wu (2017) Gibbs sampler scaffold.
run:
  seed: 0
  chains: 2
  results_dir: results
  run_id_prefix: smoke

warmup:
  config_path: configs/warmup.yaml

data:
  paths_config: configs/data_paths.yaml
  priors_config: configs/priors_example.yaml
  synthetic: true

sampler:
  sweeps: 1
  warmup_sweeps: 1
  production_sweeps: 1
  particle_gibbs_particles: 8

logging:
  level: INFO
  rich_tracebacks: true

model:
  rho_max: 0.995
  vTau_star: 60
  maturities: [3, 6, 12, 36, 60, 84, 120]
  priors_3a:
    sigma_log_omega: 1.0
    sigma_L: 0.3
    sigma_lambda: 0.5
    sigma_q_sq: 6000.0
    sigma_gamma1: 250.0
